### ISSUE TITLE
What is the proper place to send suggestions, report bugs, comment  ?

### ISSUE THREAD

**Issue by marcelpaulo** [OpenSilk/SyncthingAndroid#1]
I've just installed a [custom build](https://github.com/Zillode/SyncthingAndroid) of your ST client, and I'm downright impressed. I'd like to send some suggestions, perhaps report bugs, make comments (and compliments !): is this the proper place ? It seemed odd that there no issues registered, so it ocurred to me the discussions might be going on somewhere else.

Congratulations for this mighty fine addition to the ST family !

**Comment by rdiaz02** [comment]
As @marcelpaulo , I'd like to send some suggestions/comments/questions on the app and I wonder about the proper place. I am using the same custom build (https://github.com/Zillode/SyncthingAndroid) he is using. Anyway, thanks for the app!
