### ISSUE TITLE
UI stuck after importing config

### ISSUE THREAD

**Issue by rdiaz02** [OpenSilk/SyncthingAndroid#3]
Using the version from http://wilma.vub.ac.be/~lhoste/syncthing/unofficial/silk-0.1.50.apk (2015-05-04; sources from https://github.com/Zillode/SyncthingAndroid).

I installed the apk in a device that did not have this client previously. It created keys, etc. Then I imported the config (a zip file containing the cert.pem, key.pem and config.xml files).  The UI, however, seems forever stuck trying to start; it is still showing the device name pre-importation of config and giving the "Syncthing seems to be off or there is a problem with your internect connection". The funny thing, though, is that it is **really** working just fine (it is syncing with other devices, the other devices see it with the right version, and I can operate from the Web GUI, changing folder settings, etc). 

I turned off and on the phone, but it did not help.

**Comment by Zillode** [comment]
If this was working before, you can closed this issue and discuss it on the forum. Thanks

**Comment by rdiaz02** [comment]
No idea if it was working before. Didn't try it. I'll close the issue anyway, and move it to the forum.
